#!/usr/bin/env node

/**
 * Environment Setup Script
 * Auto-generates .env from env.example with validation
 */

const fs = require('fs');
const path = require('path');

const ENV_EXAMPLE = path.join(__dirname, '..', 'env.example');
const ENV_FILE = path.join(__dirname, '..', '.env');

// Required environment variables
const REQUIRED_VARS = [
  'PORT',
  'NODE_ENV'
];

/**
 * Read and parse env.example file
 */
function readEnvExample() {
  try {
    const content = fs.readFileSync(ENV_EXAMPLE, 'utf8');
    const lines = content.split('\n');
    const envVars = {};
    
    for (const line of lines) {
      const trimmed = line.trim();
      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }
      
      // Parse KEY=VALUE format
      const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/);
      if (match) {
        const [, key, value] = match;
        envVars[key] = value;
      }
    }
    
    return envVars;
  } catch (error) {
    console.error('Error reading env.example:', error.message);
    process.exit(1);
  }
}

/**
 * Read existing .env file
 */
function readExistingEnv() {
  if (!fs.existsSync(ENV_FILE)) {
    return {};
  }
  
  try {
    const content = fs.readFileSync(ENV_FILE, 'utf8');
    const lines = content.split('\n');
    const envVars = {};
    
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }
      
      const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/);
      if (match) {
        const [, key, value] = match;
        envVars[key] = value;
      }
    }
    
    return envVars;
  } catch (error) {
    console.error('Error reading existing .env:', error.message);
    return {};
  }
}

/**
 * Write .env file
 */
function writeEnvFile(envVars) {
  const lines = [];
  
  // Add header comment
  lines.push('# MicroPaper Mock Custodian API Configuration');
  lines.push('# Generated by setup-env.js');
  lines.push('# DO NOT EDIT THIS FILE MANUALLY - Edit env.example instead');
  lines.push('');
  
  // Add environment variables
  for (const [key, value] of Object.entries(envVars)) {
    lines.push(`${key}=${value}`);
  }
  
  try {
    fs.writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf8');
    console.log('✅ .env file created successfully');
  } catch (error) {
    console.error('Error writing .env file:', error.message);
    process.exit(1);
  }
}

/**
 * Validate required environment variables
 */
function validateEnvVars(envVars) {
  const missing = [];
  
  for (const required of REQUIRED_VARS) {
    if (!envVars[required] || envVars[required].trim() === '') {
      missing.push(required);
    }
  }
  
  if (missing.length > 0) {
    console.error('❌ Missing required environment variables:');
    missing.forEach(v => console.error(`   - ${v}`));
    return false;
  }
  
  // Validate PORT is a number
  if (envVars.PORT && isNaN(parseInt(envVars.PORT))) {
    console.error('❌ PORT must be a valid number');
    return false;
  }
  
  // Validate NODE_ENV
  const validEnvs = ['development', 'production', 'test'];
  if (envVars.NODE_ENV && !validEnvs.includes(envVars.NODE_ENV)) {
    console.warn(`⚠️  NODE_ENV should be one of: ${validEnvs.join(', ')}`);
  }
  
  return true;
}

/**
 * Main function
 */
function main() {
  console.log('🔧 Setting up environment variables...\n');
  
  // Check if env.example exists
  if (!fs.existsSync(ENV_EXAMPLE)) {
    console.error('❌ env.example file not found');
    process.exit(1);
  }
  
  // Read env.example
  const exampleVars = readEnvExample();
  console.log(`📖 Read ${Object.keys(exampleVars).length} variables from env.example`);
  
  // Read existing .env if it exists
  const existingVars = readExistingEnv();
  const hasExisting = Object.keys(existingVars).length > 0;
  
  if (hasExisting) {
    console.log(`📝 Found existing .env file with ${Object.keys(existingVars).length} variables`);
    console.log('   Preserving existing values...\n');
  }
  
  // Merge: existing values take precedence, then example values
  const mergedVars = { ...exampleVars, ...existingVars };
  
  // Validate
  if (!validateEnvVars(mergedVars)) {
    process.exit(1);
  }
  
  // Write .env file
  writeEnvFile(mergedVars);
  
  console.log('\n✨ Environment setup complete!');
  console.log('   You can now start the application with: npm start\n');
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = { main };

